const readline = require("readline").createInterface({
  input: process.stdin,
  output: process.stdout,
});

const say = require('say');

// Function to speak a given text
function speak(text) {
  say.speak(text);
}


//154 Easy Words
const wordBank = {
    easy: [
        { words: ["abdomen"], type: "[noun]", definition: "Body part containing stomach." , difficulty: 4},
        { words: ["abolish"], type: "[verb]", definition: "End or cancel officially." , difficulty: 4},
        { words: ["absence"], type: "[noun]", definition: "State of being away." , difficulty: 5},
        { words: ["absorb"], type: "[verb]", definition: "Take in or soak up." , difficulty: 2},
        { words: ["abstract"], type: "[adjective]", definition: "Not concrete or tangible." , difficulty: 5},
        { words: ["agnostic"], type: "[noun]", definition: "Person unsure about God." , difficulty: 7},
        { words: ["albeit"], type: "[conjunction]", definition: "Although or even though." , difficulty: 9},
        { words: ["alliance"], type: "[noun]", definition: "Union for mutual benefit." , difficulty: 5},
        { words: ["alphabet"], type: "[noun]", definition: "Set of letters for language." , difficulty: 4},
        { words: ["anatomical"], type: "[adjective]", definition: "Related to body structure." , difficulty: 6},
        { words: ["appetite"], type: "[noun]", definition: "Desire for food." , difficulty: 5},
        { words: ["armor"], type: "[noun]", definition: "Protective covering for defense." , difficulty: 2},
        { words: ["ash"], type: "[noun]", definition: "Powdery residue after burning." , difficulty: 1},
        { words: ["assumption"], type: "[noun]", definition: "Belief without proof." , difficulty: 5},
        { words: ["automatic"], type: "[adjective]", definition: "Working by itself." , difficulty: 5},
        { words: ["await"], type: "[verb]", definition: "Wait for something." , difficulty: 3},
        { words: ["bayonet"], type: "[noun]", definition: "Blade attached to rifle." , difficulty: 7},
        { words: ["bingo"], type: "[noun]", definition: "Game of chance with numbers." , difficulty: 3},
        { words: ["biography"], type: "[noun]", definition: "Story of someone's life." , difficulty: 4},
        { words: ["bizarre"], type: "[adjective]", definition: "Very strange or unusual." , difficulty: 5},
        { words: ["brain"], type: "[noun]", definition: "Organ for thinking." , difficulty: 1},
        { words: ["breakthrough"], type: "[noun]", definition: "Major discovery or progress." , difficulty: 6},
        { words: ["broccoli"], type: "[noun]", definition: "Green vegetable with florets." , difficulty: 6},
        { words: ["burger"], type: "[noun]", definition: "Sandwich with meat patty." , difficulty: 2},
        { words: ["burial"], type: "[noun]", definition: "Act of placing in ground." , difficulty: 6},
        { words: ["cabin"], type: "[noun]", definition: "Small house or shelter." , difficulty: 1},
        { words: ["chicken"], type: "[noun]", definition: "Farm bird or cowardly person." , difficulty: 1},
        { words: ["chronic"], type: "[adjective]", definition: "Long-lasting or persistent." , difficulty: 6},
        { words: ["circle"], type: "[noun]", definition: "Round shape with no corners." , difficulty: 1},
        { words: ["clever"], type: "[adjective]", definition: "Quick-witted or intelligent." , difficulty: 1},
        { words: ["cliff"], type: "[noun]", definition: "Steep rock face." , difficulty: 1},
        { words: ["colonel", "kernel"], type: "[noun]", definition: "Military rank or seed part." , difficulty: 7},
        { words: ["comply"], type: "[verb]", definition: "Follow rules or orders." , difficulty: 4},
        { words: ["concentration"], type: "[noun]", definition: "Focus or attention." , difficulty: 5},
        { words: ["congratulate"], type: "[verb]", definition: "Express joy for success." , difficulty: 5},
        { words: ["controversial"], type: "[adjective]", definition: "Causing disagreement." , difficulty: 7},
        { words: ["convey"], type: "[verb]", definition: "Communicate or transport." , difficulty: 2},
        { words: ["cool"], type: "[adjective]", definition: "Moderately cold or stylish." , difficulty: 1},
        { words: ["dairy"], type: "[noun]", definition: "Milk-based products." , difficulty: 2},
        { words: ["debris"], type: "[noun]", definition: "Scattered fragments." , difficulty: 5},
        { words: ["defy"], type: "[verb]", definition: "Resist or challenge." , difficulty: 5},
        { words: ["diesel"], type: "[noun]", definition: "Type of fuel." , difficulty: 5},
        { words: ["derogatory"], type: "[adjective]", definition: "Insulting or disrespectful." , difficulty: 7},
        { words: ["duck"], type: "[noun]", definition: "Water bird or avoid something." , difficulty: 1},
        { words: ["echo"], type: "[noun]", definition: "Repeated sound reflection." , difficulty: 4},
        { words: ["embassy"], type: "[noun]", definition: "Official diplomatic building." , difficulty: 6},
        { words: ["emoji"], type: "[noun]", definition: "Small digital image." , difficulty: 3},
        { words: ["enact"], type: "[verb]", definition: "Make into law." , difficulty: 6},
        { words: ["erupt"], type: "[verb]", definition: "Explode or burst out." , difficulty: 4},
        { words: ["exert"], type: "[verb]", definition: "Apply force or effort." , difficulty: 5},
        { words: ["exile"], type: "[noun]", definition: "Forced removal from home." , difficulty: 4},
        { words: ["familiar"], type: "[adjective]", definition: "Well-known or recognized." , difficulty: 3},
        { words: ["film"], type: "[noun]", definition: "Movie or thin layer." , difficulty: 1},
        { words: ["filter"], type: "[noun]", definition: "Device for removing impurities." , difficulty: 2},
        { words: ["firefighter"], type: "[noun]", definition: "Person who extinguishes fires." , difficulty: 4},
        { words: ["forbid"], type: "[verb]", definition: "Prohibit or ban." , difficulty: 4},
        { words: ["formidable"], type: "[adjective]", definition: "Inspiring fear or respect." , difficulty: 5},
        { words: ["frolic"], type: "[verb]", definition: "Play or move cheerfully." , difficulty: 7},
        { words: ["furious"], type: "[adjective]", definition: "Extremely angry." , difficulty: 4},
        { words: ["gallant"], type: "[adjective]", definition: "Brave or heroic." , difficulty: 7},
        { words: ["gazebo"], type: "[noun]", definition: "Outdoor roofed structure." , difficulty: 7},
        { words: ["gender"], type: "[noun]", definition: "Male or female identity." , difficulty: 2},
        { words: ["giant"], type: "[noun]", definition: "Very large person or thing." , difficulty: 2},
        { words: ["gold"], type: "[noun]", definition: "Precious yellow metal." , difficulty: 1},
        { words: ["greedy"], type: "[adjective]", definition: "Wanting too much." , difficulty: 1},
        { words: ["grub"], type: "[noun]", definition: "Larva or food." , difficulty: 3},
        { words: ["guideline"], type: "[noun]", definition: "Rule or principle." , difficulty: 4},
        { words: ["heresy"], type: "[noun]", definition: "Belief against doctrine." , difficulty: 7},
        { words: ["hotel"], type: "[noun]", definition: "Place for lodging." , difficulty: 2},
        { words: ["house"], type: "[noun]", definition: "Building for living." , difficulty: 2},
        { words: ["human"], type: "[noun]", definition: "Homo sapiens species." , difficulty: 1},
        { words: ["hungry"], type: "[adjective]", definition: "Needing food." , difficulty: 2},
        { words: ["immobilize"], type: "[verb]", definition: "Prevent movement." , difficulty: 6},
        { words: ["ink"], type: "[noun]", definition: "Liquid for writing." , difficulty: 2},
        { words: ["integrity"], type: "[noun]", definition: "Honesty or strong morals." , difficulty: 5},
        { words: ["intent"], type: "[noun]", definition: "Purpose or goal." , difficulty: 4},
        { words: ["intermediate"], type: "[adjective]", definition: "Between beginner and advanced." , difficulty: 6},
        { words: ["ionize"], type: "[verb]", definition: "Convert into ions." , difficulty: 7},
        { words: ["iron"], type: "[noun]", definition: "Metal element.", difficulty: 2},
        { words: ["irony"], type: "[noun]", definition: "Opposite of expected meaning." , difficulty: 6},
        { words: ["lactose"], type: "[noun]", definition: "Milk sugar." , difficulty: 6},
        { words: ["lather"], type: "[noun]", definition: "Foamy soap bubbles." , difficulty: 4},
        { words: ["length"], type: "[noun]", definition: "Measurement of distance." , difficulty: 4},
        { words: ["liable"], type: "[adjective]", definition: "Legally responsible." , difficulty: 6},
        { words: ["lightning"], type: "[noun]", definition: "Electric discharge in storm." , difficulty: 3},
        { words: ["limousine"], type: "[noun]", definition: "Luxury long car." , difficulty: 6},
        { words: ["magnificent"], type: "[adjective]", definition: "Impressively beautiful." , difficulty: 4},
        { words: ["margin"], type: "[noun]", definition: "Edge or boundary." , difficulty: 7},
        { words: ["meditate"], type: "[verb]", definition: "Focus mind deeply." , difficulty: 5},
        { words: ["microorganism"], type: "[noun]", definition: "Tiny living organism." , difficulty: 8},
        { words: ["mix"], type: "[verb]", definition: "Combine substances." , difficulty: 1},
        { words: ["monk"], type: "[noun]", definition: "Religious man." , difficulty: 3},
        { words: ["neighboring"], type: "[adjective]", definition: "Nearby or adjacent." , difficulty: 4},
        { words: ["noble", "nobel"], type: "[noun/adjective]", definition: "Honorable or prize name." , difficulty: 4},
        { words: ["noob", "newb"], type: "[noun]", definition: "Beginner or inexperienced." , difficulty: 2},
        { words: ["oasis"], type: "[noun]", definition: "Fertile desert area." , difficulty: 5},
        { words: ["obesity"], type: "[noun]", definition: "Excess body fat." , difficulty: 4},
        { words: ["offender"], type: "[noun]", definition: "Person breaking law." , difficulty: 4},
        { words: ["optimism"], type: "[noun]", definition: "Positive outlook." , difficulty: 6},
        { words: ["overdue", "overdo"], type: "[verb]", definition: "Late or excessive." , difficulty: 4},
        { words: ["palatine"], type: "[noun]", definition: "Relating to palate." , difficulty: 7},
        { words: ["paradox"], type: "[noun]", definition: "Contradictory statement." , difficulty: 6},
        { words: ["pear", "pair"], type: "[noun]", definition: "Fruit or matching set." , difficulty: 1},
        { words: ["pie", "pi"], type: "[noun]", definition: "Dessert or math constant." , difficulty: 1},
        { words: ["pigeon", "pidgin", "pidgeon"], type: "[noun]", definition: "Bird or simplified language." , difficulty: 3},
        { words: ["plethora"], type: "[noun]", definition: "Large amount." , difficulty: 5},
        { words: ["power"], type: "[noun]", definition: "Ability or energy." , difficulty: 2},
        { words: ["prank"], type: "[noun]", definition: "Trick or joke." , difficulty: 2},
        { words: ["pray", "prey"], type: "[verb]", definition: "Worship or hunt." , difficulty: 1},
        { words: ["probably"], type: "[adverb]", definition: "Likely to happen." , difficulty: 2},
        { words: ["proclamation"], type: "[noun]", definition: "Official announcement." , difficulty: 3},
        { words: ["proof"], type: "[noun]", definition: "Evidence or verification." , difficulty: 2},
        { words: ["quack"], type: "[noun]", definition: "Duck sound or fake doctor." , difficulty: 4},
        { words: ["quill"], type: "[noun]", definition: "Feather pen." , difficulty: 4},
        { words: ["rally"], type: "[noun]", definition: "Gathering or comeback." , difficulty: 2},
        { words: ["random"], type: "[adjective]", definition: "Unpredictable or arbitrary." , difficulty: 2},
        { words: ["refrain"], type: "[verb]", definition: "Hold back or chorus." , difficulty: 3},
        { words: ["refugee"], type: "[noun]", definition: "Person fleeing danger." , difficulty: 4},
        { words: ["reply"], type: "[verb]", definition: "Respond to message." , difficulty: 3},
        { words: ["robust"], type: "[adjective]", definition: "Strong or healthy." , difficulty: 3},
        { words: ["ruby"], type: "[noun]", definition: "Red gemstone." , difficulty: 2},
        { words: ["rye", "wry"], type: "[noun/adjective]", definition: "Grain or twisted expression." , difficulty: 5},
        { words: ["sashay", "sachet"], type: "[noun/verb]", definition: "Walk confidently or small bag." , difficulty: 8},
        { words: ["semicircle"], type: "[noun]", definition: "Half of a circle." , difficulty: 4},
        { words: ["shake"], type: "[verb]", definition: "Move quickly back and forth." , difficulty: 3},
        { words: ["sigh"], type: "[verb]", definition: "Exhale audibly in relief." , difficulty: 3},
        { words: ["significance"], type: "[noun]", definition: "Importance or meaning." , difficulty: 4},
        { words: ["size"], type: "[noun]", definition: "Measurement of dimensions." , difficulty: 1},
        { words: ["soda"], type: "[noun]", definition: "Carbonated soft drink." , difficulty: 1},
        { words: ["state"], type: "[noun]", definition: "Condition or political region." , difficulty: 1},
        { words: ["stereotype"], type: "[noun]", definition: "Oversimplified generalization." , difficulty: 4},
        { words: ["still"], type: "[adjective]", definition: "Motionless or quiet." , difficulty: 1},
        { words: ["strategic"], type: "[adjective]", definition: "Planned for advantage." , difficulty: 4},
        { words: ["stumble"], type: "[verb]", definition: "Trip or make a mistake." , difficulty: 4},
        { words: ["subsidy"], type: "[noun]", definition: "Government financial aid." , difficulty: 8},
        { words: ["suck"], type: "[verb]", definition: "Draw in liquid or air." , difficulty: 1},
        { words: ["syntax"], type: "[noun]", definition: "Rules for sentence structure." , difficulty: 7},
        { words: ["tangerine"], type: "[noun]", definition: "Small orange fruit." , difficulty: 6},
        { words: ["telepathy"], type: "[noun]", definition: "Mind-to-mind communication." , difficulty: 7},
        { words: ["thesis"], type: "[noun]", definition: "Main idea or argument." , difficulty: 3},
        { words: ["town"], type: "[noun]", definition: "Small urban area." , difficulty: 1},
        { words: ["transaction"], type: "[noun]", definition: "Exchange of goods or money." , difficulty: 5},
        { words: ["trauma"], type: "[noun]", definition: "Severe emotional or physical injury." , difficulty: 4},
        { words: ["twist"], type: "[verb]", definition: "Bend or rotate." , difficulty: 2},
        { words: ["uncomfortable"], type: "[adjective]", definition: "Causing discomfort.", difficulty: 5},
        { words: ["update"], type: "[verb]", definition: "Make current or improve." , difficulty: 3},
        { words: ["vague"], type: "[adjective]", definition: "Unclear or uncertain." , difficulty: 5},
        { words: ["vain", "vein"], type: "[noun/adjective]", definition: "Arrogant or blood vessel." , difficulty: 1},
        { words: ["villain"], type: "[noun]", definition: "Evil character." , difficulty: 2},
        { words: ["voluntary"], type: "[adjective]", definition: "Done by choice." , difficulty: 4},
        { words: ["water"], type: "[noun]", definition: "Essential liquid for life." , difficulty: 1},
        { words: ["word"], type: "[noun]", definition: "Unit of language." , difficulty: 1},
        { words: ["workout"], type: "[noun]", definition: "Exercise session." , difficulty: 4},
        { words: ["wrist"], type: "[noun]", definition: "Joint between hand and arm." , difficulty: 5}
    ],
    //291 medium words
    medium: [
        { words: ["abacaxi"], type: "[noun]", definition: "Brazilian pineapple.", difficulty: 7 },
        { words: ["abdomen"], type: "[noun]", definition: "Body part containing stomach.", difficulty: 3 },
        { words: ["abhorrent"], type: "[adjective]", definition: "Disgusting or repulsive.", difficulty: 6 },
        { words: ["abolish"], type: "[verb]", definition: "End or cancel officially.", difficulty: 3 },
        { words: ["abscond"], type: "[verb]", definition: "Leave secretly or escape.", difficulty: 4 },
        { words: ["absence"], type: "[noun]", definition: "State of being away.", difficulty: 2 },
        { words: ["abstract"], type: "[adjective]", definition: "Not concrete or tangible.", difficulty: 3 },
        { words: ["absquatulate"], type: "[verb]", definition: "Leave abruptly or flee.", difficulty: 8 },
        { words: ["accomplishment"], type: "[noun]", definition: "Achievement or success.", difficulty: 2 },
        { words: ["accumulation"], type: "[noun]", definition: "Gradual increase or collection.", difficulty: 3 },
        { words: ["acetaminophen"], type: "[noun]", definition: "Pain-relieving medicine.", difficulty: 6 },
        { words: ["achromatophil"], type: "[noun]", definition: "Cell that does not stain.", difficulty: 7 },
        { words: ["achromatophilia"], type: "[noun]", definition: "Love for colorless things.", difficulty: 9 },
        { words: ["acquiesce"], type: "[verb]", definition: "Accept without protest.", difficulty: 7 },
        { words: ["aegis"], type: "[noun]", definition: "Protection or sponsorship.", difficulty: 5 },
        { words: ["aerodynamic"], type: "[adjective]", definition: "Designed to reduce air resistance.", difficulty: 6 },
        { words: ["aggrandize"], type: "[verb]", definition: "Increase power or reputation.", difficulty: 5 },
        { words: ["agnostic"], type: "[noun]", definition: "Person unsure about God.", difficulty: 4 },
        { words: ["agriculture"], type: "[noun]", definition: "Farming or cultivation.", difficulty: 3 },
        { words: ["albeit"], type: "[conjunction]", definition: "Although or even though.", difficulty: 6 },
        { words: ["alliance"], type: "[noun]", definition: "Union for mutual benefit.", difficulty: 3 },
        { words: ["allotransplantation"], type: "[noun]", definition: "Organ transplant between individuals.", difficulty: 9 },
        { words: ["alphabet"], type: "[noun]", definition: "Set of letters for language.", difficulty: 2 },
        { words: ["ambiguous"], type: "[adjective]", definition: "Unclear or open to interpretation.", difficulty: 5 },
        { words: ["anachronistic"], type: "[adjective]", definition: "Out of place in time.", difficulty: 7 },
        { words: ["anaphylactic"], type: "[adjective]", definition: "Severe allergic reaction.", difficulty: 6 },
        { words: ["anatomical"], type: "[adjective]", definition: "Related to body structure.", difficulty: 5 },
        { words: ["anemone"], type: "[noun]", definition: "Sea creature or flower.", difficulty: 8 },
        { words: ["antediluvian"], type: "[adjective]", definition: "Extremely old or outdated.", difficulty: 9 },
        { words: ["apocryphal"], type: "[adjective]", definition: "Of doubtful authenticity.", difficulty: 6 },
        { words: ["appetite"], type: "[noun]", definition: "Desire for food.", difficulty: 2 },
        { words: ["articulate"], type: "[verb]", definition: "Express clearly.", difficulty: 3 },
        { words: ["assumption"], type: "[noun]", definition: "Belief without proof.", difficulty: 4 },
        { words: ["asthma"], type: "[noun]", definition: "Respiratory condition.", difficulty: 5 },
        { words: ["attorney"], type: "[noun]", definition: "Lawyer or legal representative.", difficulty: 3 },
        { words: ["automatic"], type: "[adjective]", definition: "Working by itself.", difficulty: 2 },
        { words: ["await"], type: "[verb]", definition: "Wait for something.", difficulty: 2 },
        { words: ["baccalaureate"], type: "[noun]", definition: "Academic degree or ceremony.", difficulty: 7 },
        { words: ["bandeau"], type: "[noun]", definition: "Strip of fabric or headband.", difficulty: 4 },
        { words: ["batrachophobia"], type: "[noun]", definition: "Fear of amphibians.", difficulty: 8 },
        { words: ["bayonet"], type: "[noun]", definition: "Blade attached to rifle.", difficulty: 6 },
        { words: ["benevolence"], type: "[noun]", definition: "Kindness or goodwill.", difficulty: 5 },
        { words: ["biography"], type: "[noun]", definition: "Story of someone's life.", difficulty: 2 },
        { words: ["bizarre"], type: "[adjective]", definition: "Very strange or unusual.", difficulty: 5 },
        { words: ["breakthrough"], type: "[noun]", definition: "Major discovery or progress.", difficulty: 4 },
        { words: ["broccoli"], type: "[noun]", definition: "Green vegetable with florets.", difficulty: 6 },
        { words: ["bronchitis"], type: "[noun]", definition: "Inflammation of bronchial tubes.", difficulty: 7 },
        { words: ["brusque"], type: "[adjective]", definition: "Abrupt or blunt.", difficulty: 6 },
        { words: ["bureaucracy"], type: "[noun]", definition: "Complex system of government.", difficulty: 7 },
        { words: ["burger"], type: "[noun]", definition: "Sandwich with meat patty.", difficulty: 2 },
        { words: ["capoeira"], type: "[noun]", definition: "Brazilian martial art dance.", difficulty: 8 },
        { words: ["capricious"], type: "[adjective]", definition: "Unpredictable or impulsive.", difficulty: 7 },
        { words: ["catalogue", "catalog"], type: "[noun]", definition: "List of items.", difficulty: 5 },
        { words: ["caustic"], type: "[adjective]", definition: "Corrosive or sarcastic.", difficulty: 6 },
        { words: ["charisma"], type: "[noun]", definition: "Personal charm or appeal.", difficulty: 5 },
        { words: ["chauffeur"], type: "[noun]", definition: "Professional driver.", difficulty: 8 },
        { words: ["chicken"], type: "[noun]", definition: "Farm bird or cowardly person.", difficulty: 2 },
        { words: ["chlorophyll"], type: "[noun]", definition: "Green pigment in plants.", difficulty: 7 },
        { words: ["chronic"], type: "[adjective]", definition: "Long-lasting or persistent.", difficulty: 4 },
        { words: ["circle"], type: "[noun]", definition: "Round shape with no corners.", difficulty: 2 },
        { words: ["clandestine"], type: "[adjective]", definition: "Secret or hidden.", difficulty: 6 },
        { words: ["coalescence"], type: "[noun]", definition: "Merging or blending together.", difficulty: 7 },
        { words: ["cognitive"], type: "[adjective]", definition: "Related to thinking or understanding.", difficulty: 6 },
        { words: ["colonel", "kernel"], type: "[noun]", definition: "Military rank or seed part.", difficulty: 9 },
        { words: ["combustible"], type: "[adjective]", definition: "Capable of catching fire.", difficulty: 6 },
        { words: ["comeuppance"], type: "[noun]", definition: "Deserved punishment or fate.", difficulty: 8 },
        { words: ["commodity"], type: "[noun]", definition: "Valuable product or resource.", difficulty: 5 },
        { words: ["compartmentalization"], type: "[noun]", definition: "Dividing into sections.", difficulty: 9 },
        { words: ["compunction"], type: "[noun]", definition: "Feeling of guilt or regret.", difficulty: 7 },
        { words: ["concentration"], type: "[noun]", definition: "Focus or attention.", difficulty: 4 },
        { words: ["congratulate"], type: "[verb]", definition: "Express joy for success.", difficulty: 3 },
        { words: ["contradistinguish"], type: "[verb]", definition: "Differentiate by contrast.", difficulty: 9 },
        { words: ["controversial"], type: "[adjective]", definition: "Causing disagreement.", difficulty: 6 },
        { words: ["curious"], type: "[adjective]", definition: "Eager to learn or know.", difficulty: 3 },
        { words: ["cyrillic"], type: "[noun]", definition: "Alphabet used in Slavic languages.", difficulty: 8 },
        { words: ["dauntless"], type: "[adjective]", definition: "Fearless or brave.", difficulty: 5 },
        { words: ["debris"], type: "[noun]", definition: "Scattered fragments.", difficulty: 4 },
        { words: ["deleterious"], type: "[adjective]", definition: "Harmful or damaging.", difficulty: 7 },
        { words: ["dendrochronology"], type: "[noun]", definition: "Tree ring dating.", difficulty: 8 },
        { words: ["deoxyribonucleic"], type: "[noun]", definition: "DNA molecule.", difficulty: 9 },
        { words: ["deployment"], type: "[noun]", definition: "Arrangement or movement of troops.", difficulty: 5 },
        { words: ["dichotomization"], type: "[noun]", definition: "Division into two parts.", difficulty: 8 },
        { words: ["diesel"], type: "[noun]", definition: "Type of fuel.", difficulty: 4 },
        { words: ["dilate"], type: "[verb]", definition: "Expand or widen.", difficulty: 5 },
        { words: ["disappointment"], type: "[noun]", definition: "Feeling of letdown.", difficulty: 4 },
        { words: ["doctrine"], type: "[noun]", definition: "Set of beliefs or principles.", difficulty: 5 },
        { words: ["dolphin"], type: "[noun]", definition: "Intelligent marine mammal.", difficulty: 3 },
        { words: ["elaborate"], type: "[verb]", definition: "Explain in detail.", difficulty: 4 },
        { words: ["elysian", "elision"], type: "[noun]", definition: "Heavenly or blissful / Omission of sounds in speech.", difficulty: 8 },
        { words: ["embassy"], type: "[noun]", definition: "Official diplomatic building.", difficulty: 5 },
        { words: ["encore"], type: "[noun]", definition: "Repeated performance.", difficulty: 4 },
        { words: ["endeavor"], type: "[noun]", definition: "Attempt or effort.", difficulty: 5 },
        { words: ["entrepreneur"], type: "[noun]", definition: "Business founder or innovator.", difficulty: 7 },
        { words: ["epiphany"], type: "[noun]", definition: "Sudden realization.", difficulty: 6 },
        { words: ["erratic"], type: "[adjective]", definition: "Unpredictable or inconsistent.", difficulty: 5 },
        { words: ["euphoria"], type: "[noun]", definition: "Extreme happiness.", difficulty: 6 },
        { words: ["excalibur"], type: "[noun]", definition: "Legendary sword of King Arthur.", difficulty: 7 },
        { words: ["excellent"], type: "[adjective]", definition: "Outstanding or superior.", difficulty: 3 },
        { words: ["expenditure"], type: "[noun]", definition: "Spending or cost.", difficulty: 5 },
        { words: ["exponential"], type: "[adjective]", definition: "Rapidly increasing.", difficulty: 6 },
        { words: ["familiar"], type: "[adjective]", definition: "Well-known or recognized.", difficulty: 3 },
        { words: ["favorable"], type: "[adjective]", definition: "Beneficial or positive.", difficulty: 4 },
        { words: ["fictitious"], type: "[adjective]", definition: "Not real or imaginary.", difficulty: 6 },
        { words: ["firefighter"], type: "[noun]", definition: "Person who extinguishes fires.", difficulty: 4 },
        { words: ["flamboyant"], type: "[adjective]", definition: "Showy or extravagant.", difficulty: 6 },
        { words: ["flavor", "flavour"], type: "[noun]", definition: "Taste or essence.", difficulty: 5 },
        { words: ["fluorescent"], type: "[adjective]", definition: "Glowing under light.", difficulty: 7 },
        { words: ["formidable"], type: "[adjective]", definition: "Inspiring fear or respect.", difficulty: 6 },
        { words: ["forthcoming"], type: "[adjective]", definition: "Upcoming or approaching.", difficulty: 5 },
        { words: ["fossiliferous"], type: "[adjective]", definition: "Containing fossils.", difficulty: 8 },
        { words: ["frolic"], type: "[verb]", definition: "Play or move cheerfully.", difficulty: 4 },
        { words: ["fuchsia"], type: "[noun]", definition: "Bright pink-purple color.", difficulty: 7 },
        { words: ["furious"], type: "[adjective]", definition: "Extremely angry.", difficulty: 4 },
        { words: ["gallant"], type: "[adjective]", definition: "Brave or heroic.", difficulty: 5 },
        { words: ["gastronomic"], type: "[adjective]", definition: "Related to fine dining.", difficulty: 7 },
        { words: ["gazebo"], type: "[noun]", definition: "Outdoor roofed structure.", difficulty: 6 },
        { words: ["gibberish"], type: "[noun]", definition: "Nonsensical speech.", difficulty: 5 },
        { words: ["glaucomatous"], type: "[adjective]", definition: "Related to glaucoma.", difficulty: 8 },
        { words: ["gradual"], type: "[adjective]", definition: "Happening slowly over time.", difficulty: 3 },
        { words: ["gubernatorial"], type: "[adjective]", definition: "Related to a governor.", difficulty: 7 },
        { words: ["guideline"], type: "[noun]", definition: "Rule or principle.", difficulty: 3 },
        { words: ["heresy"], type: "[noun]", definition: "Belief against doctrine.", difficulty: 6 },
        { words: ["heterozygous"], type: "[adjective]", definition: "Having different alleles.", difficulty: 7 },
        { words: ["hieroglyphics"], type: "[noun]", definition: "Ancient Egyptian writing system.", difficulty: 8 },
        { words: ["hornswoggle"], type: "[verb]", definition: "Deceive or trick.", difficulty: 8 },
        { words: ["humanitarian"], type: "[noun/adjective]", definition: "Person helping others / Concerned with human welfare.", difficulty: 5 },
        { words: ["hypermetropia"], type: "[noun]", definition: "Farsightedness.", difficulty: 8 },
        { words: ["hypothesis"], type: "[noun]", definition: "Proposed explanation or theory.", difficulty: 6 },
        { words: ["iconoclast"], type: "[noun]", definition: "Person who challenges traditions.", difficulty: 7 },
        { words: ["ideological"], type: "[adjective]", definition: "Related to ideas or beliefs.", difficulty: 6 },
        { words: ["idiom"], type: "[noun]", definition: "Phrase with figurative meaning.", difficulty: 5 },
        { words: ["imminent"], type: "[adjective]", definition: "About to happen.", difficulty: 5 },
        { words: ["immobilize"], type: "[verb]", definition: "Prevent movement.", difficulty: 6 },
        { words: ["imprisonment"], type: "[noun]", definition: "State of being jailed.", difficulty: 6 },
        { words: ["inchoate"], type: "[adjective]", definition: "Not fully developed.", difficulty: 7 },
        { words: ["incomprehensibility"], type: "[noun]", definition: "State of being impossible to understand.", difficulty: 5 },
        { words: ["indefatigable"], type: "[adjective]", definition: "Tireless or persistent.", difficulty: 8 },
        { words: ["independence"], type: "[noun]", definition: "Freedom from control.", difficulty: 4 },
        { words: ["indifference"], type: "[noun]", definition: "Lack of concern or interest.", difficulty: 5 },
        { words: ["infinitesimal"], type: "[adjective]", definition: "Extremely small.", difficulty: 7 },
        { words: ["infundibulum"], type: "[noun]", definition: "Funnel-shaped structure.", difficulty: 9 },
        { words: ["ingenious"], type: "[adjective]", definition: "Clever or inventive.", difficulty: 4 },
        { words: ["inhabitant"], type: "[noun]", definition: "Person living in a place.", difficulty: 5 },
        { words: ["integrity"], type: "[noun]", definition: "Honesty or strong morals.", difficulty: 3 },
        { words: ["intermediate"], type: "[adjective]", definition: "Between beginner and advanced.", difficulty: 4 },
        { words: ["ionize"], type: "[verb]", definition: "Convert into ions.", difficulty: 6 },
        { words: ["isthmus"], type: "[noun]", definition: "Narrow land connecting two areas.", difficulty: 8 },
        { words: ["jurisprudence"], type: "[noun]", definition: "Study of law.", difficulty: 7 },
        { words: ["juxtaposition"], type: "[noun]", definition: "Placing things side by side for contrast.", difficulty: 8 },
        { words: ["labyrinthine"], type: "[adjective]", definition: "Complicated or maze-like.", difficulty: 9 },
        { words: ["lactose"], type: "[noun]", definition: "Milk sugar.", difficulty: 4 },
        { words: ["languid"], type: "[adjective]", definition: "Lacking energy or enthusiasm.", difficulty: 5 },
        { words: ["lather"], type: "[noun]", definition: "Foamy soap bubbles.", difficulty: 3 },
        { words: ["legendary"], type: "[adjective]", definition: "Famous or well-known.", difficulty: 4 },
        { words: ["lepidopterology"], type: "[noun]", definition: "Study of butterflies and moths.", difficulty: 9 },
        { words: ["liable"], type: "[adjective]", definition: "Legally responsible.", difficulty: 4 },
        { words: ["lightning"], type: "[noun]", definition: "Electric discharge in storm.", difficulty: 6 },
        { words: ["limousine"], type: "[noun]", definition: "Luxury long car.", difficulty: 7 },
        { words: ["macabre"], type: "[adjective]", definition: "Gruesome or horrifying.", difficulty: 7 },
        { words: ["magnificent"], type: "[adjective]", definition: "Impressively beautiful.", difficulty: 5 },
        { words: ["mathematician"], type: "[noun]", definition: "Expert in mathematics.", difficulty: 7 },
        { words: ["meditate"], type: "[verb]", definition: "Focus mind deeply.", difficulty: 5 },
        { words: ["microorganism"], type: "[noun]", definition: "Tiny living organism.", difficulty: 8 },
        { words: ["milieu"], type: "[noun]", definition: "Social or cultural environment.", difficulty: 7 },
        { words: ["misconception"], type: "[noun]", definition: "Incorrect understanding.", difficulty: 6 },
        { words: ["municipal"], type: "[adjective]", definition: "Related to a city or town.", difficulty: 5 },
        { words: ["necromancer"], type: "[noun]", definition: "Person who practices magic involving the dead.", difficulty: 6 },
        { words: ["neuropsychological"], type: "[adjective]", definition: "Related to brain function and behavior.", difficulty: 9 },
        { words: ["nonplussed"], type: "[adjective]", definition: "Confused or unsure how to react.", difficulty: 7 },
        { words: ["oasis"], type: "[noun]", definition: "Fertile desert area.", difficulty: 5 },
        { words: ["obesity"], type: "[noun]", definition: "Excess body fat.", difficulty: 4 },
        { words: ["obituary"], type: "[noun]", definition: "Notice of someone's death.", difficulty: 6 },
        { words: ["oblivious"], type: "[adjective]", definition: "Unaware or not noticing.", difficulty: 5 },
        { words: ["offender"], type: "[noun]", definition: "Person breaking law.", difficulty: 4 },
        { words: ["onomatopoeia"], type: "[noun]", definition: "Word that imitates sound.", difficulty: 8 },
        { words: ["opaque"], type: "[adjective]", definition: "Not transparent or hard to understand.", difficulty: 6 },
        { words: ["optimism"], type: "[noun]", definition: "Hopefulness or positive outlook.", difficulty: 5 },
        { words: ["overdue"], type: "[adjective]", definition: "Past the expected time.", difficulty: 4 },
        { words: ["palatine"], type: "[noun]", definition: "Relating to the palate.", difficulty: 7 },
        { words: ["paradigm"], type: "[noun]", definition: "Model or example.", difficulty: 6 },
        { words: ["paradox"], type: "[noun]", definition: "Contradictory statement.", difficulty: 6 },
        { words: ["parallel"], type: "[adjective]", definition: "Equidistant and never meeting.", difficulty: 5 },
        { words: ["paraphernalia"], type: "[noun]", definition: "Equipment or accessories.", difficulty: 7 },
        { words: ["paroxysm"], type: "[noun]", definition: "Sudden outburst or attack.", difficulty: 9 },
        { words: ["participation"], type: "[noun]", definition: "Involvement in an activity.", difficulty: 5 },
        { words: ["passionate"], type: "[adjective]", definition: "Showing strong emotion.", difficulty: 4 },
        { words: ["password"], type: "[noun]", definition: "Secret code for access.", difficulty: 3 },
        { words: ["peppermint"], type: "[noun]", definition: "Minty-flavored herb or candy.", difficulty: 5 },
        { words: ["periodically"], type: "[adverb]", definition: "Occurring at intervals.", difficulty: 5 },
        { words: ["personnel"], type: "[noun]", definition: "Employees or staff.", difficulty: 6 },
        { words: ["perspicacious"], type: "[adjective]", definition: "Highly perceptive or insightful.", difficulty: 8 },
        { words: ["pestilence"], type: "[noun]", definition: "Deadly disease or plague.", difficulty: 7 },
        { words: ["pharaoh", "farrow"], type: "[noun]", definition: "Egyptian ruler / Litter of piglets.", difficulty: 9 },
        { words: ["phlegm"], type: "[noun]", definition: "Thick mucus from throat.", difficulty: 7 },
        { words: ["photographer"], type: "[noun]", definition: "Person who takes pictures.", difficulty: 5 },
        { words: ["pigeon", "pidgin", "pidgeon"], type: "[noun]", definition: "Bird or simplified language.", difficulty: 9 },
        { words: ["pirouette"], type: "[noun]", definition: "Ballet spin on one foot.", difficulty: 8 },
        { words: ["plenipotentiary"], type: "[noun]", definition: "Person with full authority.", difficulty: 9 },
        { words: ["plethora"], type: "[noun]", definition: "Large amount or excess.", difficulty: 6 },
        { words: ["pomegranate"], type: "[noun]", definition: "Fruit with red seeds.", difficulty: 7 },
        { words: ["portfolio"], type: "[noun]", definition: "Collection of work or investments.", difficulty: 5 },
        { words: ["portmanteau"], type: "[noun]", definition: "Blended word or suitcase.", difficulty: 8 },
        { words: ["predecessor"], type: "[noun]", definition: "Person who came before.", difficulty: 6 },
        { words: ["predominantly"], type: "[adverb]", definition: "Mostly or mainly.", difficulty: 5 },
        { words: ["prestidigitation"], type: "[noun]", definition: "Sleight of hand or magic tricks.", difficulty: 9 },
        { words: ["probably"], type: "[adverb]", definition: "Likely to happen.", difficulty: 3 },
        { words: ["proclamation"], type: "[noun]", definition: "Official announcement.", difficulty: 5 },
        { words: ["procrastinate"], type: "[verb]", definition: "Delay or postpone action.", difficulty: 6 },
        { words: ["prognostication"], type: "[noun]", definition: "Prediction or forecast.", difficulty: 8 },
        { words: ["pronunciation"], type: "[noun]", definition: "Way a word is spoken.", difficulty: 7 },
        { words: ["propaganda"], type: "[noun]", definition: "Biased information to influence opinion.", difficulty: 6 },
        { words: ["pulchritudinous"], type: "[adjective]", definition: "Physically beautiful.", difficulty: 9 },
        { words: ["pursuit"], type: "[noun]", definition: "Act of chasing or seeking.", difficulty: 4 },
        { words: ["pusillanimous"], type: "[adjective]", definition: "Cowardly or lacking courage.", difficulty: 8 },
        { words: ["quasquicentennial"], type: "[noun]", definition: "125th anniversary.", difficulty: 9 },
        { words: ["quill"], type: "[noun]", definition: "Feather pen.", difficulty: 4 },
        { words: ["quixotry"], type: "[noun]", definition: "Idealistic but impractical pursuit.", difficulty: 8 },
        { words: ["recession"], type: "[noun]", definition: "Economic decline.", difficulty: 6 },
        { words: ["recipient"], type: "[noun]", definition: "Person who receives something.", difficulty: 5 },
        { words: ["refrain"], type: "[verb]", definition: "Hold back or chorus.", difficulty: 5 },
        { words: ["refugee"], type: "[noun]", definition: "Person fleeing danger.", difficulty: 6 },
        { words: ["reincarnation"], type: "[noun]", definition: "Rebirth in a new form.", difficulty: 7 },
        { words: ["reliability"], type: "[noun]", definition: "Dependability or trustworthiness.", difficulty: 5 },
        { words: ["remarkable"], type: "[adjective]", definition: "Worthy of attention.", difficulty: 4 },
        { words: ["reminiscence"], type: "[noun]", definition: "Memory or recollection.", difficulty: 6 },
        { words: ["rhinorrhagia"], type: "[noun]", definition: "Severe nosebleed.", difficulty: 9 },
        { words: ["rye", "wry"], type: "[noun/adjective]", definition: "Grain or twisted expression.", difficulty: 7 },
        { words: ["sapphire"], type: "[noun]", definition: "Blue precious gemstone.", difficulty: 6 },
        { words: ["sashay", "sachet"], type: "[noun/verb]", definition: "Walk confidently or small bag.", difficulty: 8 },
        { words: ["scholarship"], type: "[noun]", definition: "Financial aid for education.", difficulty: 5 },
        { words: ["scrutiny"], type: "[noun]", definition: "Close examination or inspection.", difficulty: 6 },
        { words: ["seldom"], type: "[adverb]", definition: "Rarely or infrequently.", difficulty: 4 },
        { words: ["semicircle"], type: "[noun]", definition: "Half of a circle.", difficulty: 3 },
        { words: ["sentimental"], type: "[adjective]", definition: "Emotional or nostalgic.", difficulty: 5 },
        { words: ["separation"], type: "[noun]", definition: "Act of dividing or disconnecting.", difficulty: 6 },
        { words: ["sequacious"], type: "[adjective]", definition: "Following blindly or obediently.", difficulty: 8 },
        { words: ["sequoia"], type: "[noun]", definition: "Tall evergreen tree.", difficulty: 7 },
        { words: ["serendipity"], type: "[noun]", definition: "Unexpected good fortune.", difficulty: 6 },
        { words: ["sesquipedalian"], type: "[adjective]", definition: "Characterized by long words.", difficulty: 9 },
        { words: ["shareholder"], type: "[noun]", definition: "Person owning stock in a company.", difficulty: 5 },
        { words: ["significance"], type: "[noun]", definition: "Importance or meaning.", difficulty: 5 },
        { words: ["solidarity"], type: "[noun]", definition: "Unity or mutual support.", difficulty: 6 },
        { words: ["soliloquy"], type: "[noun]", definition: "Speech to oneself in a play.", difficulty: 8 },
        { words: ["spokesperson"], type: "[noun]", definition: "Official representative or speaker.", difficulty: 5 },
        { words: ["steadfast"], type: "[adjective]", definition: "Firm or unwavering.", difficulty: 6 },
        { words: ["stereotype"], type: "[noun]", definition: "Oversimplified generalization.", difficulty: 6 },
        { words: ["strategic"], type: "[adjective]", definition: "Planned for advantage.", difficulty: 5 },
        { words: ["subcompartmentalization", "subcompartmentalisation"], type: "[noun]", definition: "Dividing into smaller sections.", difficulty: 9 },
        { words: ["subpoena"], type: "[noun]", definition: "Legal order to appear in court.", difficulty: 7 },
        { words: ["subsidy"], type: "[noun]", definition: "Government financial aid.", difficulty: 5 },
        { words: ["supercede", "supersede"], type: "[verb]", definition: "Replace or take over.", difficulty: 7 },
        { words: ["supererogatory"], type: "[adjective]", definition: "Beyond what is required.", difficulty: 8 },
        { words: ["superferromagnetism"], type: "[noun]", definition: "Strong magnetic property.", difficulty: 9 },
        { words: ["supposedly"], type: "[adverb]", definition: "As claimed or assumed.", difficulty: 5 },
        { words: ["surveillance"], type: "[noun]", definition: "Close observation or monitoring.", difficulty: 6 },
        { words: ["susceptible"], type: "[adjective]", definition: "Easily affected or influenced.", difficulty: 5 },
        { words: ["susurration"], type: "[noun]", definition: "Soft whispering sound.", difficulty: 8 },
        { words: ["syllepsis"], type: "[noun]", definition: "Figure of speech using one word in two senses.", difficulty: 7 },
        { words: ["symmetrical"], type: "[adjective]", definition: "Balanced or evenly proportioned.", difficulty: 5 },
        { words: ["syntax"], type: "[noun]", definition: "Rules for sentence structure.", difficulty: 6 },
        { words: ["systematic"], type: "[adjective]", definition: "Organized or methodical.", difficulty: 5 },
        { words: ["syzygy"], type: "[noun]", definition: "Alignment of celestial bodies.", difficulty: 9 },
        { words: ["tangerine"], type: "[noun]", definition: "Small orange fruit.", difficulty: 4 },
        { words: ["telepathy"], type: "[noun]", definition: "Mind-to-mind communication.", difficulty: 6 },
        { words: ["thalassophobia"], type: "[noun]", definition: "Fear of deep water.", difficulty: 8 },
        { words: ["thesaurus"], type: "[noun]", definition: "Book of synonyms and antonyms.", difficulty: 5 },
        { words: ["thesis"], type: "[noun]", definition: "Main idea or argument.", difficulty: 4 },
        { words: ["transaction"], type: "[noun]", definition: "Exchange of goods or money.", difficulty: 5 },
        { words: ["translucent"], type: "[adjective]", definition: "Allowing light to pass through.", difficulty: 6 },
        { words: ["transparency"], type: "[noun]", definition: "State of being clear or open.", difficulty: 6 },
        { words: ["transportation"], type: "[noun]", definition: "Means of travel or movement.", difficulty: 5 },
        { words: ["tremendous"], type: "[adjective]", definition: "Extremely large or impressive.", difficulty: 6 },
        { words: ["uncharacteristic"], type: "[adjective]", definition: "Not typical or usual.", difficulty: 5 },
        { words: ["uncomfortable"], type: "[adjective]", definition: "Causing discomfort.", difficulty: 5 },
        { words: ["unintelligible"], type: "[adjective]", definition: "Impossible to understand.", difficulty: 6 },
        { words: ["unprecedented"], type: "[adjective]", definition: "Never done or seen before.", difficulty: 6 },
        { words: ["utilitarianism"], type: "[noun]", definition: "Philosophy of maximizing happiness.", difficulty: 7 },
        { words: ["vague"], type: "[adjective]", definition: "Unclear or uncertain.", difficulty: 5 },
        { words: ["validity"], type: "[noun]", definition: "Truth or correctness.", difficulty: 6 },
        { words: ["venerate"], type: "[verb]", definition: "Respect deeply.", difficulty: 7 },
        { words: ["verisimilitude"], type: "[noun]", definition: "Appearance of truth or reality.", difficulty: 9 },
        { words: ["villain"], type: "[noun]", definition: "Evil character.", difficulty: 6 },
        { words: ["violation"], type: "[noun]", definition: "Breaking of a rule or law.", difficulty: 5 },
        { words: ["voluntary"], type: "[adjective]", definition: "Done by choice.", difficulty: 4 },
        { words: ["warrior"], type: "[noun]", definition: "Brave fighter or soldier.", difficulty: 6 },
        { words: ["worcestershire"], type: "[noun]", definition: "Type of sauce.", difficulty: 9 },
        { words: ["worthwhile"], type: "[adjective]", definition: "Valuable or rewarding.", difficulty: 5 },
        { words: ["zephyr"], type: "[noun]", definition: "Soft gentle breeze.", difficulty: 6 },
        { words: ["zygote"], type: "[noun]", definition: "Fertilized egg cell.", difficulty: 7 }
    ],
    hard: [
        { words: ["abacaxi"], type: "[noun]", definition: "Brazilian pineapple.", difficulty: 2 },
        { words: ["absquatulate"], type: "[verb]", definition: "Leave abruptly or flee.", difficulty: 7 },
        { words: ["accommodate"], type: "[verb]", definition: "Provide space or adjust.", difficulty: 4 },
        { words: ["acculturate"], type: "[verb]", definition: "Adapt to a new culture.", difficulty: 6 },
        { words: ["acetaminophen"], type: "[noun]", definition: "Pain-relieving medicine.", difficulty: 5 },
        { words: ["achromatophil"], type: "[noun]", definition: "Cell that does not stain.", difficulty: 8 },
        { words: ["achromatophilia"], type: "[noun]", definition: "Love for colorless things.", difficulty: 9 },
        { words: ["acquiesce"], type: "[verb]", definition: "Accept without protest.", difficulty: 6 },
        { words: ["adrenocorticotrophin", "adrenocorticotropin"], type: "[noun]", definition: "Hormone regulating adrenal glands.", difficulty: 10 },
        { words: ["aegis"], type: "[noun]", definition: "Protection or sponsorship.", difficulty: 3 },
        { words: ["aggrandize"], type: "[verb]", definition: "Increase power or reputation.", difficulty: 5 },
        { words: ["agoraphobic"], type: "[adjective]", definition: "Fearful of open spaces.", difficulty: 7 },
        { words: ["allotransplantation"], type: "[noun]", definition: "Organ transplant between individuals.", difficulty: 9 },
        { words: ["ambidextrous"], type: "[adjective]", definition: "Able to use both hands.", difficulty: 4 },
        { words: ["ambiguous"], type: "[adjective]", definition: "Unclear or open to interpretation.", difficulty: 5 },
        { words: ["anachronistic"], type: "[adjective]", definition: "Out of place in time.", difficulty: 7 },
        { words: ["anaphylactic"], type: "[adjective]", definition: "Severe allergic reaction.", difficulty: 8 },
        { words: ["antediluvian"], type: "[adjective]", definition: "Extremely old or outdated.", difficulty: 9 },
        { words: ["anthropomorphization", "anthropomorphisation"], type: "[noun]", definition: "Giving human traits to non-human things.", difficulty: 10 },
        { words: ["antidisestablishmentarianism"], type: "[noun]", definition: "Opposition to church-state separation.", difficulty: 10 },
        { words: ["apocryphal"], type: "[adjective]", definition: "Of doubtful authenticity.", difficulty: 6 },
        { words: ["asphyxiation"], type: "[noun]", definition: "Lack of oxygen causing suffocation.", difficulty: 8 },
        { words: ["attorney"], type: "[noun]", definition: "Lawyer or legal representative.", difficulty: 3 },
        { words: ["arthroereisis"], type: "[noun]", definition: "Surgical correction of foot deformity.", difficulty: 9 },
        { words: ["autothaumaturgist"], type: "[noun]", definition: "Person claiming supernatural abilities.", difficulty: 10 },
        { words: ["bandeau"], type: "[noun]", definition: "Strip of fabric or headband.", difficulty: 4 },
        { words: ["borborygmus"], type: "[noun]", definition: "Stomach rumbling sound.", difficulty: 7 },
        { words: ["bourgeoisie"], type: "[noun]", definition: "Middle-class social group.", difficulty: 6 },
        { words: ["bourgeoisification"], type: "[noun]", definition: "Process of becoming middle-class.", difficulty: 9 },
        { words: ["brucellosis"], type: "[noun]", definition: "Bacterial infection from animals.", difficulty: 8 },
        { words: ["brusque"], type: "[adjective]", definition: "Abrupt or blunt.", difficulty: 5 },
        { words: ["buckminsterfullerene"], type: "[noun]", definition: "Molecule shaped like a soccer ball.", difficulty: 10 },
        { words: ["bucolic"], type: "[adjective]", definition: "Relating to rural life.", difficulty: 6 },
        { words: ["bureaucracy"], type: "[noun]", definition: "Complex system of government.", difficulty: 5 },
        { words: ["calamitous"], type: "[adjective]", definition: "Disastrous or catastrophic.", difficulty: 6 },
        { words: ["calumny"], type: "[noun]", definition: "False statement to damage reputation.", difficulty: 7 },
        { words: ["capoeira"], type: "[noun]", definition: "Brazilian martial art dance.", difficulty: 8 },
        { words: ["capricious"], type: "[adjective]", definition: "Unpredictable or impulsive.", difficulty: 6 },
        { words: ["captious"], type: "[adjective]", definition: "Overly critical or fault-finding.", difficulty: 7 },
        { words: ["chauffeur"], type: "[noun]", definition: "Professional driver.", difficulty: 4 },
        { words: ["clandestine"], type: "[adjective]", definition: "Secret or hidden.", difficulty: 6 },
        { words: ["coalescence"], type: "[noun]", definition: "Merging or blending together.", difficulty: 7 },
        { words: ["codicil"], type: "[noun]", definition: "Legal amendment to a will.", difficulty: 8 },
        { words: ["colloquialism"], type: "[noun]", definition: "Informal language or slang.", difficulty: 7 },
        { words: ["comeuppance"], type: "[noun]", definition: "Deserved punishment or fate.", difficulty: 6 },
        { words: ["commodore"], type: "[noun]", definition: "Naval officer rank.", difficulty: 5 },
        { words: ["compartmentalization"], type: "[noun]", definition: "Dividing into sections.", difficulty: 9 },
        { words: ["compunction"], type: "[noun]", definition: "Feeling of guilt or regret.", difficulty: 7 },
        { words: ["consanguine"], type: "[adjective]", definition: "Related by blood.", difficulty: 8 },
        { words: ["contradistinguish"], type: "[verb]", definition: "Differentiate by contrast.", difficulty: 9 },
        { words: ["correspondence"], type: "[noun]", definition: "Communication by letters or emails.", difficulty: 5 },
        { words: ["cyrillic"], type: "[noun]", definition: "Alphabet used in Slavic languages.", difficulty: 6 },
        { words: ["deleterious"], type: "[adjective]", definition: "Harmful or damaging.", difficulty: 6 },
        { words: ["dendrochronology"], type: "[noun]", definition: "Tree ring dating.", difficulty: 8 },
        { words: ["deoxyribonucleic"], type: "[noun]", definition: "DNA molecule.", difficulty: 9 },
        { words: ["depilatory"], type: "[noun]", definition: "Hair removal substance.", difficulty: 5 },
        { words: ["dichotomization"], type: "[noun]", definition: "Division into two parts.", difficulty: 7 },
        { words: ["discombobulate"], type: "[verb]", definition: "Confuse or bewilder.", difficulty: 6 },
        { words: ["dodecahedron"], type: "[noun]", definition: "12-sided geometric shape.", difficulty: 8 },
        { words: ["eloquent"], type: "[adjective]", definition: "Fluent or persuasive in speech.", difficulty: 5 },
        { words: ["elysian", "elision"], type: "[noun]", definition: "Heavenly or blissful/Omission of sounds in speech.", difficulty: 7 },
        { words: ["entrepreneur"], type: "[noun]", definition: "Business founder or innovator.", difficulty: 6 },
        { words: ["ethnomethodology"], type: "[noun]", definition: "Study of social interactions.", difficulty: 9 },
        { words: ["facsimile"], type: "[noun]", definition: "Exact copy or reproduction.", difficulty: 5 },
        { words: ["fjord"], type: "[noun]", definition: "Narrow sea inlet with cliffs.", difficulty: 7 },
        { words: ["floccinaucinihilipilification"], type: "[noun]", definition: "Act of regarding something as worthless.", difficulty: 10 },
        { words: ["fossiliferous"], type: "[adjective]", definition: "Containing fossils.", difficulty: 8 },
        { words: ["fuchsia"], type: "[noun]", definition: "Bright pink-purple color.", difficulty: 6 },
        { words: ["gastroenterologist"], type: "[noun]", definition: "Doctor specializing in digestive system.", difficulty: 9 },
        { words: ["gentrification"], type: "[noun]", definition: "Urban renewal causing displacement.", difficulty: 7 },
        { words: ["glaucomatous"], type: "[adjective]", definition: "Related to glaucoma.", difficulty: 8 },
        { words: ["glockenspiel"], type: "[noun]", definition: "Percussion instrument with metal bars.", difficulty: 7 },
        { words: ["glyceraldehyde"], type: "[noun]", definition: "Simple sugar molecule.", difficulty: 8 },
        { words: ["gubernatorial"], type: "[adjective]", definition: "Related to a governor.", difficulty: 6 },
        { words: ["heterozygous"], type: "[adjective]", definition: "Having different alleles.", difficulty: 7 },
        { words: ["hierarchy"], type: "[noun]", definition: "System of ranking or organization.", difficulty: 6 },
        { words: ["hieroglyphics"], type: "[noun]", definition: "Ancient Egyptian writing system.", difficulty: 8 },
        { words: ["hippopotomonstrosesquippedaliophobia"], type: "[noun]", definition: "Fear of long words.", difficulty: 10 },
        { words: ["homogeneous"], type: "[adjective]", definition: "Uniform or consistent throughout.", difficulty: 4 },
        { words: ["hypermetropia"], type: "[noun]", definition: "Farsightedness.", difficulty: 8 },
        { words: ["hypoparathyroidism"], type: "[noun]", definition: "Hormone deficiency affecting calcium levels.", difficulty: 9 },
        { words: ["iconoclast"], type: "[noun]", definition: "Person who challenges traditions.", difficulty: 6 },
        { words: ["ignominious"], type: "[adjective]", definition: "To be publically shameful.", difficulty: 6 },
        { words: ["incandescent"], type: "[adjective]", definition: "Glowing or intensely bright.", difficulty: 7 },
        { words: ["inchoate"], type: "[adjective]", definition: "Not fully developed.", difficulty: 7 },
        { words: ["incomprehensibility"], type: "[noun]", definition: "State of being impossible to understand.", difficulty: 9 },
        { words: ["indefatigable"], type: "[adjective]", definition: "Tireless or persistent.", difficulty: 8 },
        { words: ["infinitesimal"], type: "[adjective]", definition: "Extremely small.", difficulty: 8 },
        { words: ["infundibulum"], type: "[noun]", definition: "Funnel-shaped structure.", difficulty: 9 },
        { words: ["ingenious"], type: "[adjective]", definition: "Clever or inventive.", difficulty: 6 },
        { words: ["institutionalization", "institutionalisation"], type: "[noun]", definition: "Process of establishing norms or systems.", difficulty: 7 },
        { words: ["isometropia"], type: "[noun]", definition: "Equal vision in both eyes.", difficulty: 8 },
        { words: ["isthmus"], type: "[noun]", definition: "Narrow land connecting two areas.", difficulty: 7 },
        { words: ["kaleidoscope"], type: "[noun]", definition: "Tube with colorful patterns.", difficulty: 6 },
        { words: ["labyrinthine"], type: "[adjective]", definition: "Complicated or maze-like.", difficulty: 8 },
        { words: ["languid"], type: "[adjective]", definition: "Lacking energy or enthusiasm.", difficulty: 6 },
        { words: ["legislation"], type: "[noun]", definition: "Laws or legal rules.", difficulty: 7 },
        { words: ["lepidopterology"], type: "[noun]", definition: "Study of butterflies and moths.", difficulty: 8 },
        { words: ["liaison"], type: "[noun]", definition: "Communication link between groups.", difficulty: 7 },
        { words: ["macabre"], type: "[adjective]", definition: "Gruesome or horrifying.", difficulty: 7 },
        { words: ["malapropism"], type: "[noun]", definition: "Misuse of a word humorously.", difficulty: 8 },
        { words: ["martyrdom"], type: "[noun]", definition: "Sacrifice for a cause.", difficulty: 7 },
        { words: ["mellifluous"], type: "[adjective]", definition: "Pleasantly smooth or musical.", difficulty: 8 },
        { words: ["menagerie"], type: "[noun]", definition: "Collection of animals.", difficulty: 6 },
        { words: ["milieu"], type: "[noun]", definition: "Social or cultural environment.", difficulty: 7 },
        { words: ["minuscule"], type: "[adjective]", definition: "Extremely small.", difficulty: 6 },
        { words: ["monochromatic"], type: "[adjective]", definition: "Having only one color.", difficulty: 7 },
        { words: ["monosyllabic"], type: "[adjective]", definition: "Consisting of one syllable.", difficulty: 6 },
        { words: ["municipal"], type: "[adjective]", definition: "Related to a city or town.", difficulty: 6 },
        { words: ["myopic"], type: "[adjective]", definition: "Nearsighted or lacking foresight.", difficulty: 6 },
        { words: ["myriad"], type: "[noun]", definition: "A countless or extremely great number.", difficulty: 7 },
        { words: ["narcissistic"], type: "[adjective]", definition: "Excessively self-centered.", difficulty: 8 },
        { words: ["nauseous"], type: "[adjective]", definition: "Feeling sick or about to vomit.", difficulty: 6 },
        { words: ["neuroplasticity"], type: "[noun]", definition: "Brain's ability to reorganize itself.", difficulty: 9 },
        { words: ["nutritious"], type: "[adjective]", definition: "Providing nourishment.", difficulty: 5 },
        { words: ["obfuscation"], type: "[noun]", definition: "Deliberate confusion or obscurity.", difficulty: 8 },
        { words: ["onomatopoeia"], type: "[noun]", definition: "Word that imitates sound.", difficulty: 7 },
        { words: ["paradigm"], type: "[noun]", definition: "Model or example.", difficulty: 6 },
        { words: ["parallelogrammatic"], type: "[adjective]", definition: "Relating to a parallelogram.", difficulty: 9 },
        { words: ["paraphernalia"], type: "[noun]", definition: "Equipment or accessories.", difficulty: 7 },
        { words: ["parliamentary"], type: "[adjective]", definition: "Relating to a parliament.", difficulty: 6 },
        { words: ["paroxysm"], type: "[noun]", definition: "Sudden outburst or attack.", difficulty: 8 },
        { words: ["perspicacious"], type: "[adjective]", definition: "Highly perceptive or insightful.", difficulty: 8 },
        { words: ["pessimistic"], type: "[adjective]", definition: "Expecting the worst outcome.", difficulty: 6 },
        { words: ["pharaoh", "farrow"], type: "[noun]", definition: "Egyptian ruler/Litter of piglets.", difficulty: 7 },
        { words: ["phenomenon"], type: "[noun]", definition: "Remarkable event or occurrence.", difficulty: 7 },
        { words: ["phlegm"], type: "[noun]", definition: "Thick mucus from throat.", difficulty: 6 },
        { words: ["pirouette"], type: "[noun]", definition: "Ballet spin on one foot.", difficulty: 7 },
        { words: ["plenipotentiary"], type: "[noun]", definition: "Person with full authority.", difficulty: 9 },
        { words: ["pneumatic"], type: "[adjective]", definition: "Containing or operated by air.", difficulty: 7 },
        { words: ["pneumoencephalography"], type: "[noun]", definition: "X-ray imaging of brain ventricles.", difficulty: 10 },
        { words: ["polemic"], type: "[noun]", definition: "Strong verbal or written attack.", difficulty: 8 },
        { words: ["polydactyly"], type: "[noun]", definition: "Having extra fingers or toes.", difficulty: 9 },
        { words: ["polyphiloprogenitive"], type: "[adjective]", definition: "Highly prolific or fertile.", difficulty: 10 },
        { words: ["portmanteau"], type: "[noun]", definition: "Blended word or suitcase.", difficulty: 7 },
        { words: ["prestidigitation"], type: "[noun]", definition: "Sleight of hand or magic tricks.", difficulty: 9 },
        { words: ["prognostication"], type: "[noun]", definition: "Prediction or forecast.", difficulty: 8 },
        { words: ["pseudopseudohypoparathyroidism"], type: "[noun]", definition: "Genetic disorder mimicking hormone deficiency.", difficulty: 10 },
        { words: ["psychological"], type: "[adjective]", definition: "Relating to the mind.", difficulty: 5},
        { words: ["psychoneuroendocrinological"], type: "[adjective]", definition: "Relating to brain-hormone interactions.", difficulty: 10 },
        { words: ["psychoneuroimmunology"], type: "[noun]", definition: "Study of brain-immune system interactions.", difficulty: 9 },
        { words: ["psychophysicotherapeutics"], type: "[noun]", definition: "Therapy combining psychology and physics.", difficulty: 10 },
        { words: ["puerile"], type: "[adjective]", definition: "Childish or immature.", difficulty: 6 },
        { words: ["pulchritudinous"], type: "[adjective]", definition: "Physically beautiful.", difficulty: 8 },
        { words: ["pusillanimous"], type: "[adjective]", definition: "Cowardly or lacking courage.", difficulty: 7 },
        { words: ["pygmy"], type: "[noun]", definition: "Small-statured person or animal.", difficulty: 6 },
        { words: ["querimony"], type: "[noun]", definition: "Formal complaint or grievance.", difficulty: 8 },
        { words: ["quindecasyllabic"], type: "[adjective]", definition: "Having 15 syllables.", difficulty: 9 },
        { words: ["quixotry"], type: "[noun]", definition: "Idealistic but impractical pursuit.", difficulty: 8 },
        { words: ["quoddamodotative"], type: "[adjective]", definition: "Somewhat modified or altered.", difficulty: 10 },
        { words: ["rambunctious"], type: "[adjective]", definition: "Uncontrollably energetic or noisy.", difficulty: 6 },
        { words: ["rehabilitation"], type: "[noun]", definition: "Process of recovery or restoration.", difficulty: 6 },
        { words: ["reminiscence"], type: "[noun]", definition: "Memory or recollection.", difficulty: 7 },
        { words: ["rendezvous"], type: "[noun]", definition: "Meeting at an agreed time and place.", difficulty: 7 },
        { words: ["rhinorrhagia"], type: "[noun]", definition: "Severe nosebleed.", difficulty: 9 },
        { words: ["sagacious"], type: "[adjective]", definition: "Wise or insightful.", difficulty: 7 },
        { words: ["sarcophagus"], type: "[noun]", definition: "Stone coffin.", difficulty: 8 },
        { words: ["sequacious"], type: "[adjective]", definition: "Following blindly or obediently.", difficulty: 6 },
        { words: ["sequoia"], type: "[noun]", definition: "Tall evergreen tree.", difficulty: 7 },
        { words: ["serendipity"], type: "[noun]", definition: "Unexpected good fortune.", difficulty: 7 },
        { words: ["sesquipedalian"], type: "[adjective]", definition: "Characterized by long words.", difficulty: 8 },
        { words: ["silhouette"], type: "[noun]", definition: "Dark outline of a shape.", difficulty: 5 },
        { words: ["soliloquy"], type: "[noun]", definition: "Speech to oneself in a play.", difficulty: 7 },
        { words: ["sovereignty"], type: "[noun]", definition: "Supreme power or authority.", difficulty: 5 },
        { words: ["subcompartmentalization", "subcompartmentalisation"], type: "[noun]", definition: "Dividing into smaller sections.", difficulty: 9 },
        { words: ["subpoena"], type: "[noun]", definition: "Legal order to appear in court.", difficulty: 7 },
        { words: ["subterranean"], type: "[adjective]", definition: "Existing underground.", difficulty: 8 },
        { words: ["supererogatory"], type: "[adjective]", definition: "Beyond what is required.", difficulty: 8 },
        { words: ["superferromagnetism"], type: "[noun]", definition: "Strong magnetic property.", difficulty: 9 },
        { words: ["supersede", "supercede"], type: "[verb]", definition: "Replace or take over.", difficulty: 7 },
        { words: ["susurration"], type: "[noun]", definition: "Soft whispering sound.", difficulty: 8 },
        { words: ["syllepsis"], type: "[noun]", definition: "Figure of speech using one word in two senses.", difficulty: 7 },
        { words: ["symbiosis"], type: "[noun]", definition: "Mutually beneficial relationship.", difficulty: 7 },
        { words: ["syzygy"], type: "[noun]", definition: "Alignment of celestial bodies.", difficulty: 9 },
        { words: ["thalassophobia"], type: "[noun]", definition: "Fear of deep water.", difficulty: 8 },
        { words: ["therapeutic"], type: "[adjective]", definition: "Healing or beneficial.", difficulty: 6 },
        { words: ["uncharacteristic"], type: "[adjective]", definition: "Not typical or usual.", difficulty: 7 },
        { words: ["utilitarianism"], type: "[noun]", definition: "Philosophy of maximizing happiness.", difficulty: 7 },
        { words: ["verbatim"], type: "[adverb]", definition: "Word for word.", difficulty: 6 },
        { words: ["vexatious"], type: "[adjective]", definition: "Annoying or troublesome.", difficulty: 7 },
        { words: ["vulnerability"], type: "[noun]", definition: "State of being exposed to harm.", difficulty: 7 },
        { words: ["worcestershire"], type: "[noun]", definition: "Type of sauce.", difficulty: 9 },
        { words: ["xylotypographic"], type: "[adjective]", definition: "Related to woodblock printing.", difficulty: 10 },
        { words: ["zephyr"], type: "[noun]", definition: "Soft gentle breeze.", difficulty: 6 }
    ],
    //101 Extreme Words
    extreme: [
        { words: ["abacaxi"], type: "[noun]", definition: "Brazilian pineapple.", difficulty: 6 },
        { words: ["absquatulate"], type: "[verb]", definition: "Leave abruptly or flee.", difficulty: 4 },
        { words: ["acetaminophen"], type: "[noun]", definition: "Pain-relieving medicine.", difficulty: 6 },
        { words: ["achromatophil"], type: "[noun]", definition: "Cell that does not stain.", difficulty: 6 },
        { words: ["achromatophilia"], type: "[noun]", definition: "Love for colorless things.", difficulty: 7 },
        { words: ["acquiesce"], type: "[verb]", definition: "Accept without protest.", difficulty: 6 },
        { words: ["adrenocorticotrophin", "adrenocorticotropin"], type: "[noun]", definition: "Hormone regulating adrenal glands.", difficulty: 10 },
        { words: ["aegis"], type: "[noun]", definition: "Protection or sponsorship.", difficulty: 3 },
        { words: ["allotransplantation"], type: "[noun]", definition: "Organ transplant between individuals.", difficulty: 5 },
        { words: ["anachronistic"], type: "[adjective]", definition: "Out of place in time.", difficulty: 5 },
        { words: ["antediluvian"], type: "[adjective]", definition: "Extremely old or outdated.", difficulty: 6 },
        { words: ["anthropomorphization", "anthropomorphisation"], type: "[noun]", definition: "Giving human traits to non-human things.", difficulty: 6 },
        { words: ["antidisestablishmentarianism"], type: "[noun]", definition: "Opposition to church-state separation.", difficulty: 9 },
        { words: ["apocryphal"], type: "[adjective]", definition: "Of doubtful authenticity.", difficulty: 7 },
        { words: ["arthroereisis"], type: "[noun]", definition: "Surgical correction of foot deformity.", difficulty: 9 },
        { words: ["autothaumaturgist"], type: "[noun]", definition: "Person claiming supernatural abilities.", difficulty: 8 },
        { words: ["baccalaureate"], type: "[noun]", definition: "Academic degree or ceremony.", difficulty: 7 },
        { words: ["batrachophobia"], type: "[noun]", definition: "Fear of amphibians.", difficulty: 7 },
        { words: ["bogolanfini"], type: "[noun]", definition: "Malian mud cloth.", difficulty: 8 },
        { words: ["borborygmus"], type: "[noun]", definition: "Stomach rumbling sound.", difficulty: 7 },
        { words: ["bourgeoisie"], type: "[noun]", definition: "Middle-class social group.", difficulty: 7 },
        { words: ["bourgeoisification"], type: "[noun]", definition: "Process of becoming middle-class.", difficulty: 9 },
        { words: ["buckminsterfullerene"], type: "[noun]", definition: "Molecule shaped like a soccer ball.", difficulty: 10 },
        { words: ["bureaucracy"], type: "[noun]", definition: "Complex system of government.", difficulty: 7 },
        { words: ["capoeira"], type: "[noun]", definition: "Brazilian martial art dance.", difficulty: 8 },
        { words: ["capricious"], type: "[adjective]", definition: "Unpredictable or impulsive.", difficulty: 7 },
        { words: ["compartmentalization", "compartmentalisation"], type: "[noun]", definition: "Dividing into sections.", difficulty: 9 },
        { words: ["contradistinguish"], type: "[verb]", definition: "Differentiate by contrast.", difficulty: 9 },
        { words: ["convolvulaceous"], type: "[adjective]", definition: "Resembling a morning glory plant.", difficulty: 10 },
        { words: ["chupapetrepologhic"], type: "[adjective]", definition: "Highly complex or intricate.", difficulty: 10 },
        { words: ["cyrillic"], type: "[noun]", definition: "Alphabet used in Slavic languages.", difficulty: 7 },
        { words: ["dendrochronology"], type: "[noun]", definition: "Tree ring dating.", difficulty: 8 },
        { words: ["deoxyribonucleic"], type: "[noun]", definition: "DNA molecule.", difficulty: 9 },
        { words: ["dichotomization", "dichotomisation"], type: "[noun]", definition: "Division into two parts.", difficulty: 8 },
        { words: ["entrepreneur"], type: "[noun]", definition: "Business founder or innovator.", difficulty: 7 },
        { words: ["ethnomethodology"], type: "[noun]", definition: "Study of social interactions.", difficulty: 9 },
        { words: ["floccinaucinihilipilification"], type: "[noun]", definition: "Act of regarding something as worthless.", difficulty: 10 },
        { words: ["fossiliferous"], type: "[adjective]", definition: "Containing fossils.", difficulty: 8 },
        { words: ["fuchsia"], type: "[noun]", definition: "Bright pink-purple color.", difficulty: 7 },
        { words: ["gastroenterologist"], type: "[noun]", definition: "Doctor specializing in digestive system.", difficulty: 9 },
        { words: ["glyceraldehyde"], type: "[noun]", definition: "Simple sugar molecule.", difficulty: 8 },
        { words: ["gubernatorial"], type: "[adjective]", definition: "Related to a governor.", difficulty: 7 },
        { words: ["hieroglyphics"], type: "[noun]", definition: "Ancient Egyptian writing system.", difficulty: 8 },
        { words: ["hippopotomonstrosesquippedaliophobia"], type: "[noun]", definition: "Fear of long words.", difficulty: 10 },
        { words: ["honorificabilitudinity", "honourificabilitudinity"], type: "[noun]", definition: "State of being able to achieve honors.", difficulty: 10 },
        { words: ["hypoparathyroidism"], type: "[noun]", definition: "Hormone deficiency affecting calcium levels.", difficulty: 9 },
        { words: ["iconoclast"], type: "[noun]", definition: "Person who challenges traditions.", difficulty: 7 },
        { words: ["inchoate"], type: "[adjective]", definition: "Not fully developed.", difficulty: 8 },
        { words: ["incomprehensibility"], type: "[noun]", definition: "State of being impossible to understand.", difficulty: 9 },
        { words: ["infinitesimal"], type: "[adjective]", definition: "Extremely small.", difficulty: 8 },
        { words: ["infundibulum"], type: "[noun]", definition: "Funnel-shaped structure.", difficulty: 9 },
        { words: ["institutionalization", "institutionalisation"], type: "[noun]", definition: "Process of establishing norms or systems.", difficulty: 9 },
        { words: ["isthmus"], type: "[noun]", definition: "Narrow land connecting two areas.", difficulty: 7 },
        { words: ["jurisprudence"], type: "[noun]", definition: "Study of law.", difficulty: 8 },
        { words: ["labyrinthine"], type: "[adjective]", definition: "Complicated or maze-like.", difficulty: 8 },
        { words: ["languid"], type: "[adjective]", definition: "Lacking energy or enthusiasm.", difficulty: 7 },
        { words: ["lepidopterology"], type: "[noun]", definition: "Study of butterflies and moths.", difficulty: 9 },
        { words: ["milieu"], type: "[noun]", definition: "Social or cultural environment.", difficulty: 7 },
        { words: ["neuropsychological"], type: "[adjective]", definition: "Related to brain function and behavior.", difficulty: 9 },
        { words: ["oligonucleotide"], type: "[noun]", definition: "Short DNA or RNA molecule.", difficulty: 9 },
        { words: ["onomatopoeia"], type: "[noun]", definition: "Word that imitates sound.", difficulty: 8 },
        { words: ["otorhinolaryngological"], type: "[adjective]", definition: "Related to ear, nose, and throat medicine.", difficulty: 10 },
        { words: ["paradigm"], type: "[noun]", definition: "Model or example.", difficulty: 7 },
        { words: ["parallelogrammatic"], type: "[adjective]", definition: "Relating to a parallelogram.", difficulty: 9 },
        { words: ["parangatimicuaro"], type: "[noun]", definition: "A complex word with indigenous origins.", difficulty: 10 },
        { words: ["paraphernalia"], type: "[noun]", definition: "Equipment or accessories.", difficulty: 8 },
        { words: ["paroxysm"], type: "[noun]", definition: "Sudden outburst or attack.", difficulty: 9 },
        { words: ["perspicacious"], type: "[adjective]", definition: "Highly perceptive or insightful.", difficulty: 9 },
        { words: ["pneumoencephalography"], type: "[noun]", definition: "X-ray imaging of brain ventricles.", difficulty: 10 },
        { words: ["polyphiloprogenitive"], type: "[adjective]", definition: "Highly prolific or fertile.", difficulty: 10 },
        { words: ["portmanteau"], type: "[noun]", definition: "Blended word or suitcase.", difficulty: 8 },
        { words: ["prestidigitation"], type: "[noun]", definition: "Sleight of hand or magic tricks.", difficulty: 9 },
        { words: ["prognostication"], type: "[noun]", definition: "Prediction or forecast.", difficulty: 8 },
        { words: ["pseudopseudohypoparathyroidism"], type: "[noun]", definition: "Genetic disorder mimicking hormone deficiency.", difficulty: 10 },
        { words: ["psychoneuroendocrinological"], type: "[adjective]", definition: "Relating to brain-hormone interactions.", difficulty: 10 },
        { words: ["psychoneuroimmunology"], type: "[noun]", definition: "Study of brain-immune system interactions.", difficulty: 9 },
        { words: ["psychophysicotherapeutics"], type: "[noun]", definition: "Therapy combining psychology and physics.", difficulty: 10 },
        { words: ["pulchritudinous"], type: "[adjective]", definition: "Physically beautiful.", difficulty: 9 },
        { words: ["pusillanimous"], type: "[adjective]", definition: "Cowardly or lacking courage.", difficulty: 8 },
        { words: ["quindecasyllabic"], type: "[adjective]", definition: "Having 15 syllables.", difficulty: 9 },
        { words: ["quixotry"], type: "[noun]", definition: "Idealistic but impractical pursuit.", difficulty: 8 },
        { words: ["quasquicentennial"], type: "[noun]", definition: "125th anniversary.", difficulty: 9 },
        { words: ["quoddamodotative"], type: "[adjective]", definition: "Somewhat modified or altered.", difficulty: 10 },
        { words: ["radiometeorograph"], type: "[noun]", definition: "Instrument measuring atmospheric conditions.", difficulty: 9 },
        { words: ["rhinorrhagia"], type: "[noun]", definition: "Severe nosebleed.", difficulty: 9 },
        { words: ["sequoia"], type: "[noun]", definition: "Tall evergreen tree.", difficulty: 8 },
        { words: ["serendipity"], type: "[noun]", definition: "Unexpected good fortune.", difficulty: 8 },
        { words: ["sesquipedalian"], type: "[adjective]", definition: "Characterized by long words.", difficulty: 9 },
        { words: ["soliloquy"], type: "[noun]", definition: "Speech to oneself in a play.", difficulty: 8 },
        { words: ["subcompartmentalization", "subcompartmentalisation"], type: "[noun]", definition: "Dividing into smaller sections.", difficulty: 9 },
        { words: ["subpoena"], type: "[noun]", definition: "Legal order to appear in court.", difficulty: 8 },
        { words: ["supercalifragilisticexpialidocious"], type: "[adjective]", definition: "Fantastically extravagant or wonderful.", difficulty: 10 },
        { words: ["supererogatory"], type: "[adjective]", definition: "Beyond what is required.", difficulty: 8 },
        { words: ["superferromagnetism"], type: "[noun]", definition: "Strong magnetic property.", difficulty: 9 },
        { words: ["susurration"], type: "[noun]", definition: "Soft whispering sound.", difficulty: 8 },
        { words: ["syzygy"], type: "[noun]", definition: "Alignment of celestial bodies.", difficulty: 9 },
        { words: ["thalassophobia"], type: "[noun]", definition: "Fear of deep water.", difficulty: 8 },
        { words: ["utilitarianism"], type: "[noun]", definition: "Philosophy of maximizing happiness.", difficulty: 7 },
        { words: ["verisimilitude"], type: "[noun]", definition: "Appearance of truth or reality.", difficulty: 8 },
        { words: ["worcestershire"], type: "[noun]", definition: "Type of sauce.", difficulty: 9 },
        { words: ["xylotypographic"], type: "[adjective]", definition: "Related to woodblock printing.", difficulty: 10 },
    ]
};

function askDifficulty() {
  readline.question("Choose difficulty (easy, medium, hard, extreme): ", (difficulty) => {
    if (!wordBank[difficulty]) {
      console.log("Invalid difficulty. Try again.\n");
      return askDifficulty();
    }

    startGame(difficulty);
  });
}

function startGame(difficulty) {
  const wordList = wordBank[difficulty];
  const randomWordObj = wordList[Math.floor(Math.random() * wordList.length)];
  const correctWords = randomWordObj.words.map((w) => w.toLowerCase());

  // Announce the word
  speak(randomWordObj.words[0]);

  console.log("\n🗣️ Spell this word:");
  console.log(`${randomWordObj.type} ${randomWordObj.definition}`);

  readline.question("Your spelling: ", (userInput) => {
    if (correctWords.includes(userInput.trim().toLowerCase())) {
      console.log("✅ Correct! Next word...\n");
      return startGame(difficulty); // continue game
    } else {
      console.log(`❌ Incorrect. The correct answer was one of: ${correctWords.join(", ")}`);
      console.log("Game Over.");
      readline.close();
    }
  });
}


askDifficulty();